# -*- coding: utf-8 -*-
"""TASK1  PART A & PART V.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b9PVtf4Kb90yRC2vwr3GXADSHHlPwG2n

PART A
We are going to make a "Shopping List" app.

1.Run the script to start using it.

2.Put new things into the list one at a time

3.Enter the word DONE - in all CAPS - to QUIT the
program

4.And once I quit, I want the app to show me everything
that on my list.

Hint:
Step 1: Make a list to hold onto our items.

Step 2: Print out instructions on how to use the app

Step 3: Ask for new items

Step 4: Add new items to our list

Step 5: Be able to quit the app with DONE

Step 6: print out the list
"""

# As per step 1 first we create the empty list for holding the items
Shopping_List = []

# Here we defince/create the function to add, remove and view the items 

def add():
  item = input('enter the item name: ')  # asking the use to add the item
  Shopping_List.append(item)           # we add the in emptpy shoping list 
  print(item +  " has been added in your shoping list")


def remove():                          # delete the item from your shopping list
  item = input('enter the item name you wish to remove: ')
  if item in Shopping_List:
    Shopping_List.remove(item)
    print(item +  ' has been removed from your shopping list')
  else:
    print('Entered item is not in shopping list')  

  
def view(): 
  if not Shopping_List:
    print('Your shopping List is empty')
  else:
    for item in Shopping_List:
      print(item)              

 
# we set the instructions how to use this this app
while True:
  print(""" ## Select the option what would you like to do
          1. Add item to shoping list
          2. Remove  item from the shoping list
          3. Quit the applicaiton with DONE & View List ## """)

  option = int(input())
  if option ==1:
    add()
  elif option == 2:
    remove()
  elif option == 3:
    choice = input('Are you DONE:')
    if choice == 'DONE':
      break
    else:
      print('enter the correct word')
  else:
    print('enter the correct option')

print('Here is your shopping list')
view()

"""**PART B  INTERACTIVE GUESS THE NUMBER GAME;**

The computer will think of a random number from 1 to 10
as secret number.

Then ask you ( Player ) to guess the number and store as
guess number.

Compare the guess number with the secret number.

If the player guesses the right number he wins, so print
player wins and computer lose.

If the player guesses the wrong number, then he loses so
print player lose and computer wins.



"""

import random

random_number = random.randint(1,10)

while True:
  secret_number = int(input('guess the secret number : '))  # asking user to guess the number
  if secret_number == random_number:
    print('Player wins and computer lose')
    break
  elif secret_number > random_number:
    print('computer wins and Player lose  number is too high')
  else:
    print('computer wins and Palyer lose   as number is too low')

# 2nd Method by creating the function to guess the secret number
def guess_the_number():
  random_number = random.randint(1, 10)
  guess_the_number = 0
  while guess_the_number != random_number:
    guess_the_number = int(input('Guess the number between 1 to 10: '))
    if guess_the_number > random_number:
      print('Player lose and Computer wins')
    elif guess_the_number < random_number:
      print('Player Lose and Computer wins') 

  print('Player wins and Computer Lose')

guess_the_number()

